package CAPE::Utils::Cmd::Command::submit;

use strict;
use warnings;
use parent 'CAPE::Utils::Cmd::Base';

=head1 NAME

CAPE::Utils::Cmd::Command::submit - Submit files or directories to CAPE.

=head1 VERSION

0.1.0

=cut

our $VERSION = '0.1.0';

=head1 SYNOPSIS

cape_utils submit [B<-i> <config>] [B<--clock> <time>] [B<--timeout> <seconds>]
[B<--machine> <machine>] [B<--package> <package>] [B<--options> <options>]
[B<--tags> <tags>] [B<--enforce_timeout>] [B<--unique>] [B<--json>] [B<--pretty>]
[B<--quiet>] <file/dir> [<file/dir>...]

=head1 METHODS

=head2 abstract

Returns the one line description used by the command listing.

=cut

sub abstract {
	return 'submit files/dirs to CAPE';
}

=head2 usage_desc

Returns the usage string shown in help output.

=cut

sub usage_desc {
	return '%c submit %o <file/dir> [<file/dir>...]';
}

=head2 opt_spec

Returns the L<Getopt::Long::Descriptive> option spec for this command.

=over 4

=item * B<--clock> <time> - Timestamp to set the clock of the VM to. Autogenerated if undefined. Format :: mm-dd-yyy HH:MM:ss

=item * B<--timeout> <timeout> - Timeout value in seconds. Default :: 200

=item * B<--machine> <machine> - The machine to use. First available if undefined.

=item * B<--package> <package> - Package to use, if not letting CAPE decide.

=item * B<--options> <opts> - Option string to be passed via --options.

=item * B<--random> <0/1> - Randomize the order of submission. Default :: 1

=item * B<--tags> <tags> - Tags to be passed via --tags.

=item * B<--enforce_timeout> - Force it to run the entire period. Also B<--et>.

=item * B<--unique> - Only submit unique items.

=item * B<--quiet> - Do not print the output from the submission command.

=back

=cut

sub opt_spec {
	my ($class) = @_;
	return (
		[ 'clock=s',            'timestamp to set the VM clock to, format mm-dd-yyy HH:MM:ss' ],
		[ 'timeout=i',          'timeout value in seconds, default 200' ],
		[ 'machine=s',          'the machine to use, first available if undefined' ],
		[ 'package=s',          'package to use, if not letting CAPE decide' ],
		[ 'options=s',          'option string to be passed via --options' ],
		[ 'random=i',           'randomize the order of submission, default 1', { default => 1 } ],
		[ 'tags=s',             'tags to be passed via --tags' ],
		[ 'enforce_timeout|et', 'force it to run the entire period' ],
		[ 'unique',             'only submit unique items' ],
		[ 'quiet',              'do not print the output from the submission command' ],
		$class->json_opts,
		$class->ini_opt,
	);
} ## end sub opt_spec

=head2 validate_args

Ensures at least one file/dir was passed to submit.

=cut

sub validate_args {
	my ( $self, $opt, $args ) = @_;

	if ( !defined( $args->[0] ) ) {
		$self->usage_error('No files/dirs to submit specified');
	}

	return;
}

=head2 execute

Runs the command.

=cut

sub execute {
	my ( $self, $opt, $args ) = @_;

	my $quiet = $opt->{quiet};
	if ( $opt->{json} ) {
		$quiet = 1;
	}

	my $results = $self->cape_utils($opt)->submit(
		items           => $args,
		clock           => $opt->{clock},
		timeout         => $opt->{timeout},
		machine         => $opt->{machine},
		package         => $opt->{package},
		options         => $opt->{options},
		random          => $opt->{random},
		tags            => $opt->{tags},
		enforce_timeout => $opt->{enforce_timeout},
		unique          => $opt->{unique},
		quiet           => $quiet,
	);

	if ( $opt->{json} ) {
		$self->print_json( $opt, $results );
	}

	return;
} ## end sub execute

1;
