#!perl

use strict;
use warnings;
use CAPE::Utils::Cmd;

=head1 NAME

cape_utils - A utility to help with various basic tasks related to CAPEv2.

=head1 VERSION

Versioned with L<CAPE::Utils>, that being the module every command is backed by.
Ask it directly rather than going by anything written here.

    cape_utils version

=head1 SYNOPSIS

cape_utils submit [B<-i> <config>] [B<--clock> <time>] [B<--timeout> <seconds>] [B<--machine> <machine>]
[B<--package> <package>] [B<--mime-package>|B<--no-mime-package>] [B<--dry-run>] [B<--options> <options>]
[B<--tags> <tags>] [B<--platform> <platform>] [B<--enforce_timeout>] [B<--unique>] [B<--json>]
[B<--pretty>] [B<--quiet>] <file/dir> [<file/dir>...]

cape_utils resub [B<-i> <config>] ( B<-n> <incoming name> | B<-r> <task ID> ) [B<--json>] [B<--pretty>]

cape_utils running [B<-i> <config>] [B<-C>] [B<-w> <where>] [B<--json>] [B<--pretty>]

cape_utils pending [B<-i> <config>] [B<-C>] [B<-w> <where>] [B<--json>] [B<--pretty>]

cape_utils tasks [B<-i> <config>] [B<-C>] [B<-w> <where>] [B<--direction> <dir>] [B<--order> <column>] [B<--limit> <limit>] [B<--json>] [B<--pretty>]

cape_utils fail [B<-i> <config>] B<-w> <where>

cape_utils eve [B<-i> <config>]

cape_utils munge [B<-i> <config>] B<-r> <report json>

cape_utils post [B<-i> <config>] [B<-d>] B<-r> <ID>

cape_utils exec [B<-i> <config>] [B<--quiet>] [B<--verbose>] [B<--json>] [B<--pretty>] B<--> <command> [<arg>...]

cape_utils poetry [B<-i> <config>] [B<--quiet>] [B<--verbose>] [B<--json>] [B<--pretty>] B<--> <arg>...

cape_utils mime_to_packages [B<-i> <config>] [B<--as-ini>] [B<--diff>] [B<--json>] [B<--pretty>]

cape_utils commands

cape_utils help <command>

cape_utils version

=head1 DESCRIPTION

C<cape_utils> is a L<App::Cmd> based application. Each action is implemented as an
individual sub command. Run C<cape_utils commands> to list them and
C<cape_utils help E<lt>commandE<gt>> for the options available for a specific
command.

=head1 COMPATIBILITY

The pre-L<App::Cmd> command line is still accepted. Invocations using the legacy
C<cape_utils -a E<lt>actionE<gt>> form (with C<-c>/C<--config> for the INI file)
are transparently rewritten into the sub command form, so C<cape_utils -a submit
-c /etc/cape_utils.ini foo> is equivalent to C<cape_utils submit -i
/etc/cape_utils.ini foo>. Native invocations are unaffected. See
L<CAPE::Utils::Cmd/legacy_rewrite>.

=head1 GENERAL FLAGS

=head2 -i <ini>

Config INI file.

Default: /usr/local/etc/cape_utils.ini

=head2 --json

Output the result of searches or submissions as JSON.

=head2 --pretty

Pretty print the JSON output.

=head1 COMMANDS

The options for each are shown via C<cape_utils help E<lt>commandE<gt>>.

=head2 submit

Submit files/dirs to CAPE. C<--mime-package> works the package out per item from
its mime type via the mime_packages config section, and C<--dry-run> prints what
would be submitted and how without submitting anything. See L<CAPE::Utils/submit>.

=head2 resub

Resubmit a sample originally submitted via L<nergal>, located by either its
incoming name (C<-n>) or a task ID (C<-r>). See L<CAPE::Utils::Nergal/resub>.

=head2 running

Show running tasks. See L<CAPE::Utils/get_running_table>.

=head2 pending

Show pending tasks. See L<CAPE::Utils/get_pending_table>.

=head2 tasks

Show tasks. See L<CAPE::Utils/get_tasks_table>.

=head2 fail

Fail pending tasks. See L<CAPE::Utils/fail>.

=head2 eve

Process finished tasks into the EVE log. See L<CAPE::Utils/eve_process>.

=head2 munge

Munge a report JSON. See L<CAPE::Utils/munge>.

=head2 post

Perform the configured post actions for a run ID. C<-d> describes the actions
that would be taken. See L<CAPE::Utils/post>.

=head2 exec

Run an arbitrary command from the CAPE base directory, wrapped in "poetry run"
when poetry is enabled in the config, the same way submissions are executed.
Everything after C<--> is the command and its arguments. See L<CAPE::Utils/exec>.

=head2 poetry

Run an arbitrary poetry command from the CAPE base directory. Unlike L</exec>,
which wraps the command in "poetry run", everything after C<--> is handed
straight to poetry. See L<CAPE::Utils/poetry>.

=head2 mime_to_packages

Show the mime type to package settings used by C<submit --mime-package>.
C<--as-ini> prints them as INI and C<--diff> limits it to what differs from the
shipped defaults. See L<CAPE::Utils/mime_packages>.

=head1 CONFIG FILE

For this, see the docs for L<CAPE::Utils>.

Out of the box, it will work by default with CAPEv2 in it's default config.

=cut

# rewrite the legacy "-a <action>" command line into App::Cmd form; a no-op
# for native invocations
@ARGV = CAPE::Utils::Cmd->legacy_rewrite(@ARGV);

CAPE::Utils::Cmd->run;
