#!perl

use strict;
use warnings;
use CAPE::Utils::Cmd;

=head1 NAME

cape_utils - A utility to help with various basic tasks related to CAPEv2.

=head1 VERSION

0.1.0

=head1 SYNOPSIS

cape_utils submit [B<-i> <config>] [B<--clock> <time>] [B<--timeout> <seconds>] [B<--machine> <machine>]
[B<--package> <package>] [B<--options> <options>] [B<--tags> <tags>] [B<--platform> <platform>]
[B<--enforce_timeout>] [B<--unique>] [B<--json>] [B<--pretty>] [B<--quiet>] <file/dir> [<file/dir>...]

cape_utils running [B<-i> <config>] [B<-C>] [B<-w> <where>] [B<--json>] [B<--pretty>]

cape_utils pending [B<-i> <config>] [B<-C>] [B<-w> <where>] [B<--json>] [B<--pretty>]

cape_utils tasks [B<-i> <config>] [B<-C>] [B<-w> <where>] [B<--direction> <dir>] [B<--order> <column>] [B<--limit> <limit>] [B<--json>] [B<--pretty>]

cape_utils fail [B<-i> <config>] B<-w> <where>

cape_utils eve [B<-i> <config>]

cape_utils munge [B<-i> <config>] B<-r> <report json>

cape_utils post [B<-i> <config>] B<-r> <report json>

cape_utils commands

cape_utils help <command>

=head1 DESCRIPTION

C<cape_utils> is a L<App::Cmd> based application. Each action is implemented as an
individual sub command. Run C<cape_utils commands> to list them and
C<cape_utils help E<lt>commandE<gt>> for the options available for a specific
command.

=head1 COMPATIBILITY

The pre-L<App::Cmd> command line is still accepted. Invocations using the legacy
C<cape_utils -a E<lt>actionE<gt>> form (with C<-c>/C<--config> for the INI file)
are transparently rewritten into the sub command form, so C<cape_utils -a submit
-c /etc/cape_utils.ini foo> is equivalent to C<cape_utils submit -i
/etc/cape_utils.ini foo>. Native invocations are unaffected. See
L<CAPE::Utils::Cmd/legacy_rewrite>.

=head1 GENERAL FLAGS

=head2 -i <ini>

Config INI file.

Default: /usr/local/etc/cape_utils.ini

=head2 --json

Output the result of searches or submissions as JSON.

=head2 --pretty

Pretty print the JSON output.

=head1 COMMANDS

=head2 submit

Submit files/dirs to CAPE. See L<CAPE::Utils::Cmd::Command::submit>.

=head2 running

Show running tasks. See L<CAPE::Utils::Cmd::Command::running>.

=head2 pending

Show pending tasks. See L<CAPE::Utils::Cmd::Command::pending>.

=head2 tasks

Show tasks. See L<CAPE::Utils::Cmd::Command::tasks>.

=head2 fail

Fail pending tasks. See L<CAPE::Utils::Cmd::Command::fail>.

=head2 eve

Invoke CAPE::Utils->eve_process. See L<CAPE::Utils::Cmd::Command::eve>.

=head2 munge

Munge a report JSON. See L<CAPE::Utils::Cmd::Command::munge>.

=head2 post

Perform the post actions for a run. See L<CAPE::Utils::Cmd::Command::post>.

=head1 CONFIG FILE

For this, see the docs for L<CAPE::Utils>.

Out of the box, it will work by default with CAPEv2 in it's default config.

=cut

# rewrite the legacy "-a <action>" command line into App::Cmd form; a no-op
# for native invocations
@ARGV = CAPE::Utils::Cmd->legacy_rewrite(@ARGV);

CAPE::Utils::Cmd->run;
